### ISSUE TITLE
loopStart, loopEnd API

### ISSUE THREAD

**Issue by dy** [muxinc/media-offset#2]
Hey @luwes!
First of all great job, that's required feature.

I was just working on exact same functionality in [wavearea](https://github.com/dy/wavearea) - looping audio fragments for user selection.
The way I implemented it is creating a new audio with slice of data and substituting for the main audio.
This gives better results for small chunks that need to be looped.
But it's not scalable solution, and extra burden, unlike media-offset.

I tried porting media-offset and found a couple of things.
1. First, it's not clear if that's possible to create it for `Audio` instances in JS, it seems to observe `<audio>` elements in document, right? `Audio` instances don't seem to welcome `dataset-` attributes. [_AudioBufferSourceNode_](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/loopStart) for that purpose has `loopStart` and `loopEnd` properties, I wonder if you'd look into exporting a function sort of `mediaOffset(mediaElement, {start, end})`.
2. Second, loop iteration produces slightly inconsistent sound. I guess precise looping is not the main purpose of this package, to make it precise it'd need microseconds in setTimeout. I wonder what are the possible ways to increase precision and what's the available limit for this method.
3. Third, it's not fully clear how to update offsets - is that enough to just update `data-offset` attribute? 
4. It also seems I encountered some playback bug, but I will investigate.

Overall I'd love to integrate it with wavearea if these points can be facilitated. 
Please let me know if these points are of any interest.

**Comment by luwes** [comment]
thanks @dy! wavearea's approach is really interesting, I'll have to look into it more deeply.

1. great idea, I'll definitely add that. I didn't think of the element-less audio/media instances
2. hmm yes, this might be tricky with such increased precision. I'll see if this can be improved. 
  do you happen to have a audio example where this is easily detected?
3. this should work but I'll do some more testing

thanks for the feedback, very useful!

**Comment by dy** [comment]
I've extracted logic into a bit simplified [play-clip](https://github.com/dy/wavearea/blob/692420cd3a3a82b9b2b56c43a14761ccc4b32d86/src/play-loop.js) function (in wavearea), capable of playing/looping any fragment of _Audio_ element.
It has a bit streamlined `clip.start`, `clip.end` values. 
It shows very good results even for small loopable chunks (less than 1024 samples) - can test it [here](https://dy.github.io/wavearea/?src=https://upload.wikimedia.org/wikipedia/commons/c/cf/Caja_de_m%C3%BAsica_(PianoConcerto5_Beethoven).ogg).
It seems 10ms throttling is safe for 1024 frames blocks, since one such block is ~23ms.

This method is better than decoding and looping data itself from implementation point, so I'm going to close this.
Thanks @luwes!
